import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./Components/organisms/Header";
import Effect from "./Components/organisms/Effect";
import CustomCursor from "./Components/organisms/CurstomCursor";
import Footer from "./Components/organisms/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative max-w-[1920px] m-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomCursor />
        <Effect />
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
